# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: false
sudo: false
cache: packages

r:
  - release
    env:
      - VDIFFR_RUN_TESTS=true
      - VDIFFR_LOG_PATH="../vdiffr.Rout.fail"
  - devel
    env: _R_CHECK_SYSTEM_CLOCK_=false
  
r_binary_packages:
  - Rcpp
  - RcppArmadillo
  - coda